# Generated by Django 5.0.1 on 2024-01-29 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60, verbose_name="Nombres")),
                (
                    "last_name",
                    models.CharField(max_length=60, verbose_name="apellidos"),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Nombres completos"
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        choices=[
                            ("0", "CONTADOR"),
                            ("1", "ADMINISTRADOR"),
                            ("2", "ECONOMISTA"),
                            ("3", "OTRO"),
                        ],
                        max_length=1,
                        verbose_name="Trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mi Empleado",
                "verbose_name_plural": "Empleados de la empresa",
                "ordering": ["-first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Habilidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hablidad", models.CharField(max_length=50, verbose_name="Habilidad")),
            ],
            options={
                "verbose_name": "Habilidad",
                "verbose_name_plural": "Habilidades Empleados",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Material"
                    ),
                ),
                ("unidad", models.CharField(max_length=20, verbose_name="Unidad")),
            ],
            options={
                "verbose_name": "insumo",
                "verbose_name_plural": "insumos",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Sector"
                    ),
                ),
            ],
            options={
                "verbose_name": "sector",
                "verbose_name_plural": "sectores",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="HabilidadEmpleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="descripcion"
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedidos.empleado",
                    ),
                ),
                (
                    "habilidades",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedidos.habilidades",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="empleado",
            name="habilidades",
            field=models.ManyToManyField(
                blank=True,
                through="pedidos.HabilidadEmpleado",
                to="pedidos.habilidades",
            ),
        ),
        migrations.CreateModel(
            name="MaterialesPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("detail", models.TextField(blank=True, max_length=100)),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedidos.material",
                    ),
                ),
            ],
            options={
                "verbose_name": "material",
                "verbose_name_plural": "materiales",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Obra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Obra")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Ubicación"),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("0", "Escolar"),
                            ("1", "Infraestructura"),
                            ("2", "Intendencia"),
                            ("3", "Salud"),
                        ],
                        max_length=1,
                        verbose_name="Area",
                    ),
                ),
                ("contacto", models.CharField(blank=True, max_length=100)),
                (
                    "movil",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tec asignado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("validated", models.BooleanField(default=False)),
                (
                    "materiales",
                    models.ManyToManyField(
                        blank=True,
                        through="pedidos.MaterialesPedido",
                        to="pedidos.material",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pedidos.obra"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pedidos.sector"
                    ),
                ),
            ],
            options={
                "verbose_name": "pedido",
                "verbose_name_plural": "pedidos",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="materialespedido",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pedidos.pedido",
            ),
        ),
    ]
