# Generated by Django 5.0.1 on 2024-01-26 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iniciarpedidosector",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pedidos.obra",
                verbose_name="Obra",
            ),
        ),
        migrations.AlterField(
            model_name="iniciarpedidosector",
            name="validated",
            field=models.BooleanField(default=False, verbose_name="Aprobado"),
        ),
    ]
