# Generated by Django 5.0.1 on 2024-02-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="memoria",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Memoria"
            ),
        ),
    ]
