# Generated by Django 5.0.1 on 2024-01-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="user",
            field=models.CharField(default="null", max_length=100),
            preserve_default=False,
        ),
    ]
