# Generated by Django 5.0.1 on 2024-02-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obra",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Obra"),
        ),
    ]
