# Generated by Django 5.0.1 on 2024-01-29 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialespedido",
            name="detail",
            field=models.TextField(blank=True, max_length=50, verbose_name="Detalle"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de solicitud"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tec asignado",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="validated",
            field=models.BooleanField(default=False, verbose_name="Validado"),
        ),
    ]
