# Generated by Django 5.0.1 on 2024-01-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_obra_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="obra",
            old_name="name",
            new_name="obra",
        ),
    ]
