# Generated by Django 5.0.1 on 2024-01-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_alter_iniciarpedidosector_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iniciarpedidosector",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Memoria"
            ),
        ),
    ]
