# Generated by Django 5.0.1 on 2024-03-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_alter_obra2_entrega_alter_obra2_fecha_finalizada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obra2",
            name="codObra",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Cod. Obra"
            ),
        ),
    ]
