# Generated by Django 5.0.1 on 2024-02-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_pedido_memoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="memoria",
            field=models.TextField(
                blank=True,
                help_text="En este campo, debes explicar brevemente el problema que quieres resolver y la solución que propones con los materiales que solicitas. Así, podrás justificar tu petición y agilizar el trámite de aprobación y compra de los recursos. Usa un lenguaje claro, conciso y preciso para expresar tu idea.",
                max_length=500,
                null=True,
                verbose_name="Memoria",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="validated",
            field=models.BooleanField(default=False, verbose_name="Autorizado"),
        ),
    ]
