# Generated by Django 5.0.1 on 2024-01-29 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_alter_materialespedido_detail_alter_pedido_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialespedido",
            name="detail",
        ),
    ]
