# Generated by Django 5.0.1 on 2024-02-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_alter_obra_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obra",
            name="cp",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="CP"
            ),
        ),
    ]
