# Generated by Django 5.0.1 on 2024-01-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_alter_iniciarpedidosector_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iniciarpedidosector",
            options={
                "ordering": ["-id"],
                "verbose_name": "iniciar pedido",
                "verbose_name_plural": "iniciar pedidos",
            },
        ),
    ]
