# Generated by Django 5.0.1 on 2024-01-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_remove_materialespedido_detail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habilidadempleado",
            name="empleado",
        ),
        migrations.RemoveField(
            model_name="habilidadempleado",
            name="habilidades",
        ),
        migrations.DeleteModel(
            name="Empleado",
        ),
        migrations.DeleteModel(
            name="HabilidadEmpleado",
        ),
        migrations.DeleteModel(
            name="Habilidades",
        ),
    ]
