# Generated by Django 5.0.1 on 2024-03-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_alter_obra2_codobra"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="propuesta",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="En este campo, debes explicar brevemente la solución que quieres implementar.",
                max_length=1500,
                null=True,
                verbose_name="Propuesta de solución",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="memoria",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="En este campo, debes explicar brevemente el problema que quieres resolver.",
                max_length=1500,
                null=True,
                verbose_name="Planteo de problema",
            ),
        ),
    ]
