# Generated by Django 5.0.1 on 2024-02-03 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_material_referencia_alter_pedido_memoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Proveedor"
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Referencia"
                    ),
                ),
            ],
            options={
                "verbose_name": "proveedor",
                "verbose_name_plural": "proveedores",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="material",
            name="rubro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pedidos.rubros",
                verbose_name="Rubro",
            ),
        ),
    ]
