# Generated by Django 5.0.1 on 2024-01-25 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_alter_iniciarpedidosector_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iniciarpedidosector",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pedidos.material",
                verbose_name="Material",
            ),
        ),
        migrations.AlterField(
            model_name="iniciarpedidosector",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pedidos.sector",
                verbose_name="Sector",
            ),
        ),
    ]
