# Generated by Django 5.0.1 on 2024-01-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_alter_obra_contacto_alter_obra_telefono_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iniciarpedidosector",
            name="user",
            field=models.CharField(max_length=100),
        ),
    ]
