# Generated by Django 5.0.1 on 2024-03-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_rename_memoria_pedido_problema"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="memoria",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=1000,
                null=True,
                verbose_name="Memoria",
            ),
        ),
    ]
