# Generated by Django 5.0.1 on 2024-01-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_alter_iniciarpedidosector_material_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iniciarpedidosector",
            name="validated",
            field=models.BooleanField(default=False, verbose_name="Aprovado"),
        ),
    ]
