# Generated by Django 5.0.1 on 2024-02-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_rubros_material_rubro"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rubros",
            options={
                "ordering": ["name"],
                "verbose_name": "rubro",
                "verbose_name_plural": "rubros",
            },
        ),
        migrations.AlterField(
            model_name="rubros",
            name="name",
            field=models.CharField(max_length=150, unique=True, verbose_name="Rubro"),
        ),
    ]
