# Generated by Django 5.0.1 on 2024-01-25 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0006_iniciarpedidosector_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="iniciarpedidosector",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
