# Generated by Django 5.0.1 on 2024-02-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0006_alter_rubros_options_alter_rubros_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obra",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Obra"),
        ),
    ]
