# Generated by Django 5.0.1 on 2024-02-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0007_alter_obra_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Material"),
        ),
    ]
