# Generated by Django 5.0.1 on 2024-01-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0007_iniciarpedidosector_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iniciarpedidosector",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
        ),
        migrations.AlterField(
            model_name="iniciarpedidosector",
            name="validated",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Aprovado"
            ),
        ),
    ]
