# Generated by Django 5.0.1 on 2024-03-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0008_alter_pedido_memoria_alter_pedido_problema_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="memoria",
            field=models.TextField(
                blank=True,
                help_text="Generado por IA...",
                max_length=3000,
                null=True,
                verbose_name="Memoria",
            ),
        ),
    ]
