# Generated by Django 5.0.1 on 2024-02-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0008_alter_material_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="material",
            options={
                "ordering": ["rubro", "name"],
                "verbose_name": "insumo",
                "verbose_name_plural": "insumos",
            },
        ),
    ]
