# Generated by Django 5.0.1 on 2024-02-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0009_alter_material_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Material"
            ),
        ),
    ]
