# Generated by Django 5.0.1 on 2024-02-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0010_alter_material_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="a_proveedor",
            field=models.BooleanField(default=False, verbose_name="A Proveedor"),
        ),
    ]
