# Generated by Django 5.0.1 on 2024-02-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0012_pedido_orden_compra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="orden_compra",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Orden de compra",
            ),
        ),
    ]
